
const DAY_NAMES={'2026-08-20':'Giovedì 20 agosto 2026','2026-08-21':'Venerdì 21 agosto 2026','2026-08-22':'Sabato 22 agosto 2026','2026-08-23':'Domenica 23 agosto 2026'};
const GROUPS={A:['DUCKS','ÉRD INDIANS HUNGARY','DIVING DUCKS','LONDON MONARCHS','RONCHI NBP','KIEV Baseball'],B:['TIGERS','BEAVERS METROSTARS VIENNA','LONDON ARCHERS','FUN & PLAY','RANGERS REDIPUGLIA','RADVILIŠKIS']};
const KEY='torneo_u12_2026_results';
function getResults(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function saveScore(game,side,value){const r=getResults();r[game]=r[game]||{};if(value==='')delete r[game][side];else r[game][side]=Math.max(0,parseInt(value,10));localStorage.setItem(KEY,JSON.stringify(r));}
function isPhase(m,filter){return filter==='all'||(filter==='FINALE'?m.phase.startsWith('FINALE'):m.phase===filter)}
function scoreBox(m,side,val){return `<input class="score" aria-label="Punteggio ${side===1?m.team1:m.team2}" type="number" min="0" inputmode="numeric" value="${val??''}" data-game="${m.game}" data-side="${side}">`}
function matchRow(m,r){const final=m.phase.startsWith('FINALE'),u10=m.group==='U10';const done=r[m.game]&&r[m.game][1]!==undefined&&r[m.game][2]!==undefined;return `<tr><td class="game">${m.game}</td><td>${m.time}</td><td><span class="phase ${final?'final':u10?'u10':''}">${m.phase}</span></td><td class="teams"><div class="versus"><strong>${m.team1}</strong>${scoreBox(m,1,r[m.game]?.[1])}<span>–</span>${scoreBox(m,2,r[m.game]?.[2])}<strong class="right">${m.team2}</strong></div></td><td class="status ${done?'done':''}">${done?'Risultato inserito':'Da giocare'}</td></tr>`}
function initCalendar(){const dates=[...new Set(MATCHES.map(m=>m.date))];let active='all';const box=document.getElementById('days'),calendar=document.getElementById('calendar');box.innerHTML=`<button class="daytab active" data-date="all">Tutte le giornate</button>`+dates.map(d=>`<button class="daytab" data-date="${d}">${DAY_NAMES[d].replace(' 2026','')}</button>`).join('');function render(){const field=document.getElementById('fieldFilter').value,phase=document.getElementById('phaseFilter').value,r=getResults();let html='';dates.filter(d=>active==='all'||active===d).forEach(d=>{const dayMatches=MATCHES.filter(m=>m.date===d&&(field==='all'||m.field===field)&&isPhase(m,phase));if(!dayMatches.length)return;html+=`<section class="day-section"><div class="day-head"><h2>${DAY_NAMES[d]}</h2><span>${dayMatches.length} incontri</span></div>`;[...new Set(dayMatches.map(m=>m.field))].forEach(v=>{const ms=dayMatches.filter(m=>m.field===v);html+=`<div class="venue"><h3>${v}</h3><div class="table-wrap"><table><thead><tr><th>Gara</th><th>Orario</th><th>Fase</th><th>Squadre e risultato</th><th class="hide-mobile">Stato</th></tr></thead><tbody>${ms.map(m=>matchRow(m,r)).join('')}</tbody></table></div></div>`});html+='</section>'});calendar.innerHTML=html||'<div class="card empty">Nessun incontro corrisponde ai filtri.</div>';calendar.querySelectorAll('.score').forEach(i=>i.addEventListener('input',e=>{saveScore(e.target.dataset.game,e.target.dataset.side,e.target.value);const tr=e.target.closest('tr'),scores=[...tr.querySelectorAll('.score')];const done=scores.every(x=>x.value!=='');const s=tr.querySelector('.status');s.textContent=done?'Risultato inserito':'Da giocare';s.classList.toggle('done',done)}));}
box.addEventListener('click',e=>{if(!e.target.dataset.date)return;active=e.target.dataset.date;box.querySelectorAll('.daytab').forEach(b=>b.classList.toggle('active',b===e.target));render()});document.getElementById('fieldFilter').addEventListener('change',render);document.getElementById('phaseFilter').addEventListener('change',render);document.getElementById('reset').addEventListener('click',()=>{if(confirm('Cancellare tutti i risultati inseriti?')){localStorage.removeItem(KEY);render()}});render()}
function calculate(group){const stats={};GROUPS[group].forEach(t=>stats[t]={team:t,g:0,w:0,l:0,pf:0,pa:0,diff:0,pct:0});const r=getResults();MATCHES.filter(m=>m.group===group).forEach(m=>{const a=r[m.game]?.[1],b=r[m.game]?.[2];if(a===undefined||b===undefined||a===b)return;const s1=stats[m.team1],s2=stats[m.team2];s1.g++;s2.g++;s1.pf+=a;s1.pa+=b;s2.pf+=b;s2.pa+=a;if(a>b){s1.w++;s2.l++}else{s2.w++;s1.l++}});Object.values(stats).forEach(s=>{s.diff=s.pf-s.pa;s.pct=s.g?s.w/s.g:0});return Object.values(stats).sort((a,b)=>b.pct-a.pct||b.diff-a.diff||b.pf-a.pf||a.team.localeCompare(b.team,'it'))}
function standingsTable(group){const rows=calculate(group);return `<table><thead><tr><th>#</th><th>Squadra</th><th>G</th><th>V</th><th>P</th><th>PF</th><th>PS</th><th>Diff</th><th>PCT</th></tr></thead><tbody>${rows.map((s,i)=>`<tr><td class="rank">${i+1}</td><td><span class="team-dot"></span><strong>${s.team}</strong></td><td>${s.g}</td><td>${s.w}</td><td>${s.l}</td><td>${s.pf}</td><td>${s.pa}</td><td>${s.diff>0?'+':''}${s.diff}</td><td>${s.pct.toFixed(3).replace('0.','.')}</td></tr>`).join('')}</tbody></table>`}
function renderStandings(){document.getElementById('groupA').innerHTML=standingsTable('A');document.getElementById('groupB').innerHTML=standingsTable('B')}
